insert into states(state_ab, covid_count, covid_death, trajectory_death, trajectory_hospitalize, trajectory_test, state_name) VALUES 
('AL', null, null, null, null, null, 'Alabama'), 
('AK', null, null, null, null, null, 'Alaska'), 
('AZ', null, null, null, null, null, 'Arizona'), 
('AR', null, null, null, null, null, 'Arkansas'), 
('CA', null, null, null, null, null, 'California'), 
('CO', null, null, null, null, null, 'Colorado'), 
('CT', null, null, null, null, null, 'Conneticut'), 
('DE', null, null, null, null, null, 'Delaware'), 
('FL', null, null, null, null, null, 'Florida'), 
('GA', null, null, null, null, null, 'Georgia'), 
('HI', null, null, null, null, null, 'Hawaii'), 
('ID', null, null, null, null, null, 'Idaho'), 
('IL', null, null, null, null, null, 'Illinois'), 
('IN', null, null, null, null, null, 'Indiana'), 
('IA', null, null, null, null, null, 'Iowa'), 
('KS', null, null, null, null, null, 'Kansas'), 
('KY', null, null, null, null, null, 'Kentucky'), 
('LA', null, null, null, null, null, 'Louisiana'), 
('ME', null, null, null, null, null, 'Maine'), 
('MD', null, null, null, null, null, 'Maryland'), 
('MA', null, null, null, null, null, 'Massachusetts'), 
('MI', null, null, null, null, null, 'Michigan'), 
('MN', null, null, null, null, null, 'Minnesota'), 
('MS', null, null, null, null, null, 'Mississippi'), 
('MO', null, null, null, null, null, 'Missouri'), 
('MT', null, null, null, null, null, 'Montana'), 
('NE', null, null, null, null, null, 'Nebraska'), 
('NV', null, null, null, null, null, 'Nevada'), 
('NH', null, null, null, null, null, 'New Hampshire'), 
('NJ', null, null, null, null, null, 'New Jersey'), 
('NM', null, null, null, null, null, 'New Mexico'), 
('NY', null, null, null, null, null, 'New York'), 
('NC', null, null, null, null, null, 'North Carolina'), 
('ND', null, null, null, null, null, 'North Dakota'), 
('OH', null, null, null, null, null, 'Ohio'), 
('OK', null, null, null, null, null, 'Oklahoma'), 
('OR', null, null, null, null, null, 'Oregon'), 
('PA', null, null, null, null, null, 'Pennsylvania'), 
('RI', null, null, null, null, null, 'Rhode Island'), 
('SC', null, null, null, null, null, 'South Carolina'), 
('SD', null, null, null, null, null, 'South Dakota'), 
('TN', null, null, null, null, null, 'Tennesse'), 
('TX', null, null, null, null, null, 'Texas'), 
('UT', null, null, null, null, null, 'Utah'), 
('VT', null, null, null, null, null, 'Vermont'), 
('VA', null, null, null, null, null, 'Virginia'), 
('WA', null, null, null, null, null, 'Washington'), 
('WV', null, null, null, null, null, 'West Virginia'), 
('WI', null, null, null, null, null, 'Wisconi'), 
('WY', null, null, null, null, null, 'Wyoming'), 
('AS', null, null, null, null, null, 'American Samoa'), 
('DC', null, null, null, null, null, 'District of Columbia'), 
('GU', null, null, null, null, null, 'Guam'), 
('MP', null, null, null, null, null, 'Northern Mariana Islands'), 
('PR', null, null, null, null, null, 'Puerto Rico'), 
('VI', null, null, null, null, null, 'Virgin Islands');


